# Common Linux config. By default we limit conan building to one variation as
# that's what we want for source-only packages.
linux: &linux
  os: linux
  sudo: required
  language: python
  python: "3.6"
  services:
    - docker
  env: CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64 CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7

osx: &osx
  os: osx
  language: generic

stages:
  - bootstrap0
  - bootstrap1
  - level0
  - level1
  - level2
  - level3
  - level4
  - level5
  - level6
  - level7
  - level8
  - level9
  - level10
  - level11
  - level12
  - level13
  - level14
  - level15

jobs:
  include:
    - stage: bootstrap0
      <<: *linux
      env: REPO=boost-build CONAN_ARCHS=x86,x86_64
    - stage: bootstrap1
      <<: *linux
      env: REPO=boost-generator

install:
  - chmod +x .travis/run.sh
  - chmod +x .travis/install.sh
  - ./.travis/install.sh
  - git clone -b ${TRAVIS_BRANCH} https://github.com/bincrafters/conan-${REPO} ${REPO}
  - cd ${REPO}

script:
  - ../.travis/run.sh
