# Common Linux config alias.
linux: &linux
  os: linux
  sudo: required
  language: python
  python: "3.6"
  services:
    - docker

osx: &osx
  os: osx
  language: generic

xcode83: &xcode83
  osx_image: xcode8.3
  <<: *osx

xcode94: &xcode90
  osx_image: xcode9
  <<: *osx

xcode94: &xcode91
  osx_image: xcode9.1
  <<: *osx

xcode94: &xcode94
  osx_image: xcode9.4
  <<: *osx

xcode10: &xcode10
  osx_image: xcode10
  <<: *osx

language: generic

matrix:
  fast_finish: true

env:
  global:
    - CONAN_USERNAME=bincrafters
    - CONAN_LOGIN_USERNAME=grafikrobot
    - CONAN_UPLOAD_ONLY_WHEN_STABLE=0
    - CONAN_SHARED_OPTION_NAME=
    - GCC_4="CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=conanio/gcc49"
    - GCC_5="CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=conanio/gcc5"
    - GCC_6="CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6"
    - GCC_7="CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7"
    - GCC_8="CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc8"
    - CLANG_39="CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=conanio/clang39"
    - CLANG_40="CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=conanio/clang40"
    - CLANG_50="CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=conanio/clang50"
    - CLANG_60="CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60"
    - XCODE_83="CONAN_APPLE_CLANG_VERSIONS=8.3"
    - XCODE_90="CONAN_APPLE_CLANG_VERSIONS=9.0"
    - XCODE_91="CONAN_APPLE_CLANG_VERSIONS=9.1"
    - XCODE_94="CONAN_APPLE_CLANG_VERSIONS=9.4"
    - XCODE_10="CONAN_APPLE_CLANG_VERSIONS=10.0"

install:
  - chmod +x .travis/run.sh
  - chmod +x .travis/install.sh
  - ./.travis/install.sh
  - export REPO_BRANCH=`dirname $TRAVIS_BRANCH`
  - echo $REPO_BRANCH
  - git clone -b $REPO_BRANCH https://github.com/bincrafters/conan-$REPO $REPO
  - cd $REPO

script:
  - &run ../.travis/run.sh

stages:
{stages}

jobs:
  include:
{jobs}
