# Common Linux config alias.
linux: &linux
  os: linux
  sudo: required
  language: python
  python: "3.6"
  services:
    - docker

osx: &osx
  os: osx
  language: generic

xcode73: &xcode73
  osx_image: xcode7.3
  <<: *osx

xcode83: &xcode83
  osx_image: xcode8.3
  <<: *osx

xcode90: &xcode90
  osx_image: xcode9
  <<: *osx

language: generic

matrix:
  fast_finish: true

env:
  global:
    - CONAN_USERNAME=bincrafters
    - CONAN_LOGIN_USERNAME=grafikrobot
    - CONAN_UPLOAD_ONLY_WHEN_STABLE=0
    - CONAN_SHARED_OPTION_NAME=
    - SOURCE_ONLY="CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64 CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40"
    - GCC_4="CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49"
    - GCC_5="CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5"
    - GCC_6="CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6"
    - GCC_7="CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7"
    - CLANG_39="CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39"
    - CLANG_40="CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40"
    - XCODE_73="CONAN_APPLE_CLANG_VERSIONS=7.3"
    - XCODE_81="CONAN_APPLE_CLANG_VERSIONS=8.1"
    - XCODE_83="CONAN_APPLE_CLANG_VERSIONS=8.3"
    - XCODE_90="CONAN_APPLE_CLANG_VERSIONS=9.0"
    <<: *linux

install:
  - chmod +x .travis/run.sh
  - chmod +x .travis/install.sh
  - ./.travis/install.sh
  - export REPO_BRANCH=`dirname $TRAVIS_BRANCH`
  - echo $REPO_BRANCH
  - git clone -b $REPO_BRANCH https://github.com/bincrafters/conan-$REPO $REPO
  - cd $REPO

script:
  - &run ../.travis/run.sh

stages:
  - bootstrap0
  - bootstrap1
  - level0
  - level1
  - level2
  - level3
  - level4
  - level5group
  - level5
  - level6
  - level7
  - level8group
  - level8
  - level9
  - level10
  - level11group
  - level11
  - level12
  - level13
  - level14group
  - level14
  - level15


jobs:
  include:
    - stage: bootstrap0
      env: REPO=boost_build
    - stage: bootstrap1
      env: REPO=boost-package-tools
    - stage: bootstrap1
      env: REPO=boost_generator
    - stage: level0
      env: REPO=boost_callable_traits
    - stage: level0
      env: REPO=boost_compatibility
    - stage: level0
      env: REPO=boost_config
    - stage: level0
      env: REPO=boost_predef
    - stage: level0
      env: REPO=boost_preprocessor
    - stage: level1
      env: REPO=boost_assert
    - stage: level1
      env: REPO=boost_io
    - stage: level1
      env: REPO=boost_mp11
    - stage: level1
      env: REPO=boost_preprocessor
    - stage: level1
      env: REPO=boost_static_assert
    - stage: level1
      env: REPO=boost_vmd
    - stage: level1
      env: REPO=boost_winapi
    - stage: level2
      env: REPO=boost_core
    - stage: level2
      env: REPO=boost_throw_exception
    - stage: level3
      env: REPO=boost_align
    - stage: level3
      env: REPO=boost_array
    - stage: level3
      env: REPO=boost_bind
    - stage: level3
      env: REPO=boost_integer
    - stage: level3
      env: REPO=boost_logic
    - stage: level3
      env: REPO=boost_move
    - stage: level3
      env: REPO=boost_system
    - stage: level3
      env: REPO=boost_type_traits
    - stage: level4
      env: REPO=boost_atomic
    - stage: level4
      env: REPO=boost_crc
    - stage: level4
      env: REPO=boost_smart_ptr
    - stage: level4
      env: REPO=boost_tuple
    - stage: level5group
      env: REPO=boost_exception
    - stage: level5group
      env: REPO=boost_level5group
    - stage: level5
      env: REPO=boost_concept_check
    - stage: level5
      env: REPO=boost_conversion
    - stage: level5
      env: REPO=boost_detail
    - stage: level5
      env: REPO=boost_function
    - stage: level5
      env: REPO=boost_function_types
    - stage: level5
      env: REPO=boost_functional
    - stage: level5
      env: REPO=boost_fusion
    - stage: level5
      env: REPO=boost_iterator
    - stage: level5
      env: REPO=boost_mpl
    - stage: level5
      env: REPO=boost_optional
    - stage: level5
      env: REPO=boost_type_index
    - stage: level5
      env: REPO=boost_typeof
    - stage: level5
      env: REPO=boost_utility
    - stage: level6
      env: REPO=boost_any
    - stage: level6
      env: REPO=boost_endian
    - stage: level6
      env: REPO=boost_format
    - stage: level6
      env: REPO=boost_gil
    - stage: level6
      env: REPO=boost_hana
    - stage: level6
      env: REPO=boost_intrusive
    - stage: level6
      env: REPO=boost_lambda
    - stage: level6
      env: REPO=boost_multi_array
    - stage: level6
      env: REPO=boost_numeric_conversion
    - stage: level6
      env: REPO=boost_numeric_interval
    - stage: level6
      env: REPO=boost_polygon
    - stage: level6
      env: REPO=boost_qvm
    - stage: level6
      env: REPO=boost_rational
    - stage: level6
      env: REPO=boost_regex
    - stage: level6
      env: REPO=boost_scope_exit
    - stage: level6
      env: REPO=boost_tokenizer
    - stage: level6
      env: REPO=boost_tti
    - stage: level7
      env: REPO=boost_container
    - stage: level7
      env: REPO=boost_local_function
    - stage: level7
      env: REPO=boost_range
    - stage: level7
      env: REPO=boost_ratio
    - stage: level7
      env: REPO=boost_signals
    - stage: level8group
      env: REPO=boost_level8group
    - stage: level8
      env: REPO=boost_chrono
    - stage: level8
      env: REPO=boost_circular_buffer
    - stage: level8
      env: REPO=boost_filesystem
    - stage: level8
      env: REPO=boost_foreach
    - stage: level8
      env: REPO=boost_lexical_cast
    - stage: level8
      env: REPO=boost_math
    - stage: level8
      env: REPO=boost_proto
    - stage: level8
      env: REPO=boost_unordered
    - stage: level9
      env: REPO=boost_algorithm
    - stage: level9
      env: REPO=boost_phoenix
    - stage: level9
      env: REPO=boost_program_options
    - stage: level9
      env: REPO=boost_python
    - stage: level9
      env: REPO=boost_random
    - stage: level9
      env: REPO=boost_stacktrace
    - stage: level9
      env: REPO=boost_timer
    - stage: level9
      env: REPO=boost_variant
    - stage: level9
      env: REPO=boost_xpressive
    - stage: level10
      env: REPO=boost_iostreams
    - stage: level10
      env: REPO=boost_multiprecision
    - stage: level10
      env: REPO=boost_parameter
    - stage: level10
      env: REPO=boost_test
    - stage: level11group
      env: REPO=boost_level11group
    - stage: level11
      env: REPO=boost_date_time
    - stage: level11
      env: REPO=boost_heap
    - stage: level11
      env: REPO=boost_locale
    - stage: level11
      env: REPO=boost_lockfree
    - stage: level11
      env: REPO=boost_metaparse
    - stage: level11
      env: REPO=boost_pool
    - stage: level11
      env: REPO=boost_serialization
    - stage: level11
      env: REPO=boost_spirit
    - stage: level11
      env: REPO=boost_thread
    - stage: level12
      env: REPO=boost_context
    - stage: level12
      env: REPO=boost_convert
    - stage: level12
      env: REPO=boost_dll
    - stage: level12
      env: REPO=boost_dynamic_bitset
    - stage: level12
      env: REPO=boost_geometry
    - stage: level12
      env: REPO=boost_icl
    - stage: level12
      env: REPO=boost_interprocess
    - stage: level12
      env: REPO=boost_msm
    - stage: level12
      env: REPO=boost_multi_index
    - stage: level12
      env: REPO=boost_numeric_ublas
    - stage: level12
      env: REPO=boost_ptr_container
    - stage: level12
      env: REPO=boost_sort
    - stage: level12
      env: REPO=boost_statechart
    - stage: level12
      env: REPO=boost_type_erasure
    - stage: level12
      env: REPO=boost_units
    - stage: level12
      env: REPO=boost_uuid
    - stage: level13
      env: REPO=boost_accumulators
    - stage: level13
      env: REPO=boost_assign
    - stage: level13
      env: REPO=boost_coroutine
    - stage: level13
      env: REPO=boost_coroutine2
    - stage: level13
      env: REPO=boost_fiber
    - stage: level13
      env: REPO=boost_flyweight
    - stage: level13
      env: REPO=boost_poly_collection
    - stage: level13
      env: REPO=boost_property_tree
    - stage: level13
      env: REPO=boost_signals
    - stage: level13
      env: REPO=boost_wave
    - stage: level14group
      env: REPO=boost_level14group
    - stage: level14
      env: REPO=boost_asio
    - stage: level14
      env: REPO=boost_bimap
    - stage: level14
      env: REPO=boost_compute
    - stage: level14
      env: REPO=boost_disjoint_sets
    - stage: level14
      env: REPO=boost_graph
    - stage: level14
      env: REPO=boost_graph_parallel
    - stage: level14
      env: REPO=boost_log
    - stage: level14
      env: REPO=boost_mpi
    - stage: level14
      env: REPO=boost_property_map
    - stage: level15
      env: REPO=boost_beast
    - stage: level15
      env: REPO=boost_numeric_odeint
    - stage: level15
      env: REPO=boost_process

